---
# tasks file for docker
- name: apt update
  apt:
    update_cache: true

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: make directory
  file:
    path: "/etc/apt/keyrings"
    state: directory

- name: Add Docker's official GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_os_family }}/gpg |\
    sudo gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg

- name: Use the following command to set up the repository
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/{{ ansible_os_family }} $(lsb_release -cs) stable" |\
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: apt update
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Create docker group
  group:
    name: docker

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.16.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
