---
# tasks file for docker
- hosts: localhost
  become: true
  vars_files:
    - ../defaults/main.yml
    - ../vars/main.yml
  tasks:
    - include_tasks: docker.yml

    - name: apt upgrade
      apt:
        upgrade: "yes"
