---
# tasks file for grafana
- name: copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "/root/grafana/"

- name: Run Grafana
  docker_compose:
    project_src: "/root/grafana"
    files:
      - docker-compose.yml
