---
# tasks file for minikube
- name: download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /root/

- name: install minikube
  shell: install /root/minikube-linux-amd64 /usr/local/bin/minikube
